/**
 * Every named path segment used across all API modules.
 * Numeric IDs are NOT listed here — they pass through the proxy as-is.
 * This list is the single source of truth for both the init route
 * (which aliases each segment) and the proxy handler (which decodes them).
 */
export const KNOWN_SEGMENTS = [
  "activate",
  "addresses",
  "admin",
  "admin-update",
  "approve",
  "areas",
  "auth",
  "banners",
  "block",
  "blocks",
  "brands",
  "cart",
  "categories",
  "cities",
  "company",
  "dashboard",
  "deactivate",
  "default",
  "delivery",
  "delivery-companies",
  "delivery-options",
  "featured",
  "follow",
  "follows",
  "for-you",
  "ids",
  "impersonate",
  "items",
  "login",
  "logout",
  "me",
  "options",
  "orders",
  "prices",
  "products",
  "profile",
  "quote",
  "register",
  "reject",
  "reviews",
  "search",
  "self-delivery",
  "status",
  "toggle",
  "toggle-active",
  "track-view",
  "tree",
  "users",
  "variant",
  "variants",
  "vendor",
  "vendor-applications",
  "vendors",
  "wishlist",
] as const;
